### ISSUE TITLE
No resource found

### ISSUE THREAD

**Issue by stratomda** [rosjava/android_extras#18]
Trying to compile android_extras and I am getting various errors complaining about missing resources. 
Here is one example:
"Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Borderless.Colored'."

@adamantivm Any ideas? Have you compiled android_extras?

**Comment by stratomda** [comment]
@adamantivm do i need to bump the compiledSdkVersion to 25 on the modules that have dependencies on android_10? It looks as if android_10 is now built with the appcompat 25 but I am not very good with gradle. Thanks for the help.

**Comment by adamantivm** [comment]
thanks for the catch and the fix @stratomda
